version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

# Налаштування для приховування реклами
# (працює тільки для платних акаунтів)
features:
  - search.highlighting

# Додаткові налаштування
formats:
  - pdf
  - htmlzip

# Налаштування для кращого SEO та індексації
search:
  ranking:
    api/index.rst: 2
    usage.rst: 3
